import { z } from 'zod';
import { roleScopeSchema } from './auth';

/**
 * The permission catalogue: every key the API actually enforces, grouped the way an
 * administrator thinks about them rather than the way they are named.
 *
 * Generated by reading every `requirePermission(context, '...')` call and every
 * `context.permissions.has('...')` check in `apps/api/src`, not invented. A key appears here only
 * because some service already refuses a request without it — the Access Control UI can offer
 * exactly what the backend enforces and nothing it doesn't.
 *
 * `*` is deliberately absent: it is the tenant wildcard `ORG_ADMIN` carries, not a capability an
 * administrator composes into a custom role. `assertGrantable` (`RbacService`) still rejects a
 * caller who tries to grant it anyway; this list just never offers it as a checkbox.
 */
export type PermissionCatalogueEntry = {
  key: string;
  label: string;
  module: string;
};

export const PERMISSION_CATALOGUE: PermissionCatalogueEntry[] = [
  // --- Organization -------------------------------------------------------------------------
  { key: 'organizations.read', label: 'View organization', module: 'Organization' },
  { key: 'organizations.update', label: 'Edit organization details', module: 'Organization' },
  { key: 'organizations.deactivate', label: 'Deactivate organization', module: 'Organization' },
  { key: 'branches.read', label: 'View branches', module: 'Organization' },
  { key: 'branches.write', label: 'Manage branches', module: 'Organization' },
  { key: 'members.read', label: 'View members', module: 'Organization' },
  { key: 'members.write', label: 'Add members', module: 'Organization' },
  { key: 'rbac.read', label: 'View roles and permissions', module: 'Organization' },
  { key: 'rbac.write', label: 'Manage roles and permissions', module: 'Organization' },
  {
    key: 'approval-policies.read',
    label: 'View approval routing',
    module: 'Organization',
  },
  {
    key: 'approval-policies.write',
    label: 'Manage approval routing',
    module: 'Organization',
  },

  // --- Employees ------------------------------------------------------------------------------
  { key: 'employees.read', label: 'View own employee record', module: 'Employees' },
  { key: 'employees.read.all', label: 'View every employee record', module: 'Employees' },
  { key: 'employees.write', label: 'Edit employee records', module: 'Employees' },
  { key: 'employees.branches.write', label: 'Assign employee branches', module: 'Employees' },
  { key: 'employees.compensation.write', label: 'Edit compensation', module: 'Employees' },
  { key: 'employees.access.write', label: 'Link employee to a login', module: 'Employees' },
  { key: 'employees.sessions.revoke', label: 'Revoke employee sessions', module: 'Employees' },

  // --- Attendance -----------------------------------------------------------------------------
  { key: 'attendance.read', label: 'View own attendance', module: 'Attendance' },
  { key: 'attendance.read.all', label: 'View everyone’s attendance', module: 'Attendance' },
  { key: 'attendance.write', label: 'Punch and record attendance', module: 'Attendance' },
  {
    key: 'attendance.corrections.write',
    label: 'Request a correction',
    module: 'Attendance',
  },
  {
    key: 'attendance.corrections.decide',
    label: 'Approve corrections',
    module: 'Attendance',
  },
  {
    key: 'attendance.preferences.read',
    label: 'View capture settings',
    module: 'Attendance',
  },
  {
    key: 'attendance.preferences.write',
    label: 'Manage capture settings',
    module: 'Attendance',
  },
  { key: 'attendance.webauthn.enroll', label: 'Enroll a passkey', module: 'Attendance' },
  { key: 'attendance.webauthn.assert', label: 'Use a passkey to punch', module: 'Attendance' },
  { key: 'attendance.webauthn.revoke', label: 'Revoke a passkey', module: 'Attendance' },

  // --- Leave ----------------------------------------------------------------------------------
  { key: 'leave.requests.read', label: 'View own leave requests', module: 'Leave' },
  { key: 'leave.requests.read.all', label: 'View everyone’s leave requests', module: 'Leave' },
  { key: 'leave.requests.write', label: 'Raise a leave request', module: 'Leave' },
  { key: 'leave.requests.decide', label: 'Approve leave requests', module: 'Leave' },
  { key: 'leave.balances.read', label: 'View own leave balance', module: 'Leave' },
  { key: 'leave.balances.read.all', label: 'View everyone’s leave balance', module: 'Leave' },
  { key: 'leave.balances.adjust', label: 'Adjust a leave balance', module: 'Leave' },
  { key: 'leave.types.read', label: 'View leave types', module: 'Leave' },
  { key: 'leave.types.write', label: 'Manage leave types', module: 'Leave' },

  // --- Timesheets -----------------------------------------------------------------------------
  { key: 'timesheets.read', label: 'View own timesheets', module: 'Timesheets' },
  { key: 'timesheets.read.all', label: 'View everyone’s timesheets', module: 'Timesheets' },
  { key: 'timesheets.write', label: 'Log time', module: 'Timesheets' },
  { key: 'timesheets.submit', label: 'Submit a timesheet', module: 'Timesheets' },
  { key: 'timesheets.decide', label: 'Approve timesheets', module: 'Timesheets' },

  // --- Payroll --------------------------------------------------------------------------------
  { key: 'payroll.payslips.read', label: 'View own payslips', module: 'Payroll' },
  { key: 'payroll.payslips.read.all', label: 'View everyone’s payslips', module: 'Payroll' },
  { key: 'payroll.employee-profile.read', label: 'View own salary profile', module: 'Payroll' },
  { key: 'payroll.employee-profile.write', label: 'Edit salary profiles', module: 'Payroll' },
  { key: 'payroll.preview.read', label: 'Preview own pay', module: 'Payroll' },
  { key: 'payroll.ledger.read', label: 'View own pay ledger', module: 'Payroll' },
  { key: 'payroll.ledger.read.all', label: 'View everyone’s pay ledger', module: 'Payroll' },
  { key: 'payroll.runs.read', label: 'View payroll runs', module: 'Payroll' },
  { key: 'payroll.runs.write', label: 'Create payroll runs', module: 'Payroll' },
  { key: 'payroll.runs.calculate', label: 'Calculate a payroll run', module: 'Payroll' },
  { key: 'payroll.runs.correct', label: 'Correct a released run', module: 'Payroll' },
  { key: 'payroll.adjustments.write', label: 'Add payroll adjustments', module: 'Payroll' },
  { key: 'payroll.advances.read', label: 'View own salary advances', module: 'Payroll' },
  { key: 'payroll.advances.request', label: 'Request a salary advance', module: 'Payroll' },
  { key: 'payroll.advances.approve', label: 'Approve salary advances', module: 'Payroll' },
  { key: 'payroll.payments.read', label: 'View payroll payments', module: 'Payroll' },
  { key: 'payroll.payments.write', label: 'Mark payroll payments', module: 'Payroll' },
  { key: 'payroll.calendars.read', label: 'View payroll calendar', module: 'Payroll' },
  { key: 'payroll.calendars.write', label: 'Manage payroll calendar', module: 'Payroll' },
  { key: 'payroll.components.read', label: 'View pay components', module: 'Payroll' },
  { key: 'payroll.components.write', label: 'Manage pay components', module: 'Payroll' },
  { key: 'payroll.policy.read', label: 'View payroll policy', module: 'Payroll' },
  { key: 'payroll.policy.write', label: 'Manage payroll policy', module: 'Payroll' },
  { key: 'payroll.compliance.read', label: 'View own statutory records', module: 'Payroll' },
  {
    key: 'payroll.compliance.read.all',
    label: 'View everyone’s statutory records',
    module: 'Payroll',
  },
  { key: 'payroll.compliance.write', label: 'Manage statutory records', module: 'Payroll' },

  // --- Teams and projects -----------------------------------------------------------------------
  { key: 'teams.read', label: 'View teams', module: 'Teams & Projects' },
  { key: 'teams.write', label: 'Manage teams', module: 'Teams & Projects' },
  { key: 'projects.read', label: 'View projects', module: 'Teams & Projects' },
  { key: 'projects.write', label: 'Manage projects', module: 'Teams & Projects' },

  // --- Files ----------------------------------------------------------------------------------
  { key: 'files.read', label: 'View own files', module: 'Files' },
  { key: 'files.read.all', label: 'View everyone’s files', module: 'Files' },
  { key: 'files.write', label: 'Upload and delete files', module: 'Files' },

  // --- Shifts ---------------------------------------------------------------------------------
  { key: 'shifts.read', label: 'View shifts', module: 'Shifts' },
  { key: 'shifts.write', label: 'Manage shifts', module: 'Shifts' },
];

export const PERMISSION_KEYS = new Set(PERMISSION_CATALOGUE.map((entry) => entry.key));

/** The catalogue grouped by module, in catalogue order, for a grouped picker UI. */
export function groupPermissionCatalogue(): Array<{
  module: string;
  entries: PermissionCatalogueEntry[];
}> {
  const groups = new Map<string, PermissionCatalogueEntry[]>();
  for (const entry of PERMISSION_CATALOGUE) {
    const list = groups.get(entry.module) ?? [];
    list.push(entry);
    groups.set(entry.module, list);
  }
  return [...groups.entries()].map(([module, entries]) => ({ module, entries }));
}

// --- Role and member management, matching what UsersController actually accepts -----------------

export const roleWithPermissionsSchema = z.object({
  id: z.string().uuid(),
  organizationId: z.string().uuid().nullable(),
  code: z.string(),
  name: z.string(),
  description: z.string().nullable().optional(),
  scope: roleScopeSchema,
  branchId: z.string().uuid().nullable(),
  isSystem: z.boolean(),
  permissions: z.array(z.object({ permission: z.object({ key: z.string() }) })),
});
export type RoleWithPermissions = z.infer<typeof roleWithPermissionsSchema>;

export const memberRoleSchema = z.object({
  userRoleId: z.string().uuid(),
  id: z.string().uuid(),
  code: z.string(),
  name: z.string(),
  scope: roleScopeSchema,
  branchId: z.string().uuid().nullable(),
});

export const organizationMemberSchema = z.object({
  userId: z.string().uuid(),
  email: z.string(),
  displayName: z.string(),
  isActive: z.boolean(),
  joinedAt: z.string(),
  roles: z.array(memberRoleSchema),
});
export type OrganizationMember = z.infer<typeof organizationMemberSchema>;

function parseList<T>(schema: z.ZodType<T>, payload: unknown): T[] | null {
  const items =
    Array.isArray(payload) || payload === null || payload === undefined
      ? payload
      : ((payload as { items?: unknown }).items ?? payload);
  const result = z.array(schema).safeParse(items);
  return result.success ? result.data : null;
}

export function parseRoleList(payload: unknown): RoleWithPermissions[] | null {
  return parseList(roleWithPermissionsSchema, payload);
}

export function parseMemberList(payload: unknown): OrganizationMember[] | null {
  return parseList(organizationMemberSchema, payload);
}

/**
 * Where an employee stands on having a login of their own.
 *
 * An employee record and a login are separate things in this system, and the gap between them is
 * a real state an administrator has to be able to see and act on — not an error. These are the
 * four positions an employee can be in.
 */
export const EMPLOYEE_ACCESS_CODE_STATES = [
  /** Employee record exists, nobody has started giving them access. */
  'NO_ACCOUNT',
  /** A code is outstanding and still valid. */
  'CODE_ISSUED',
  /** A code was issued but its window has passed; issuing a new one is the way forward. */
  'CODE_EXPIRED',
  /** A login exists and is attached. They can sign in. */
  'ACTIVE',
] as const;

export type EmployeeAccessCodeState = (typeof EMPLOYEE_ACCESS_CODE_STATES)[number];

export const employeeAccessCodeStatusSchema = z.object({
  state: z.enum(EMPLOYEE_ACCESS_CODE_STATES),
  /** When the outstanding code stops working. Null unless one is outstanding. */
  expiresAt: z.string().nullable(),
  issuedAt: z.string().nullable(),
});

export type EmployeeAccessCodeStatus = z.infer<typeof employeeAccessCodeStatusSchema>;

/** The plaintext code, returned by the one response that creates it and never again. */
export const issuedAccessCodeSchema = z.object({
  code: z.string(),
  expiresAt: z.string(),
});

export type IssuedAccessCode = z.infer<typeof issuedAccessCodeSchema>;

/**
 * What an employee is shown after their code checks out, before they choose a password.
 *
 * Deliberately thin: enough for them to recognise the organization and themselves, and nothing
 * that would make a valid code worth harvesting for the information it reveals.
 */
export const accessCodePreviewSchema = z.object({
  organizationName: z.string(),
  employeeName: z.string(),
  employeeNumber: z.string(),
});

export type AccessCodePreview = z.infer<typeof accessCodePreviewSchema>;

export function parseAccessCodeStatus(payload: unknown): EmployeeAccessCodeStatus | null {
  const result = employeeAccessCodeStatusSchema.safeParse(payload);
  return result.success ? result.data : null;
}

export function parseAccessCodePreview(payload: unknown): AccessCodePreview | null {
  const result = accessCodePreviewSchema.safeParse(payload);
  return result.success ? result.data : null;
}
