export interface EmployeeSeedData {
  empNo: string;
  firstName: string;
  lastName: string;
  email: string;
  role: 'ORG_ADMIN' | 'MANAGER' | 'EMPLOYEE';
  gross: number;
}

export interface HolidaySeedData {
  date: string;
  name: string;
  isOptional: boolean;
}

export const PERMISSIONS: string[] = [
  'organizations.read',
  'organizations.update',
  'branches.read',
  'branches.write',
  'members.read',
  'members.write',
  'rbac.read',
  'rbac.write',
  'approval-policies.read',
  'approval-policies.write',
  'employees.read',
  'employees.read.all',
  'employees.write',
  'employees.branches.write',
  'employees.compensation.write',
  'employees.access.write',
  'attendance.read',
  'attendance.read.all',
  'attendance.write',
  'attendance.corrections.write',
  'attendance.corrections.decide',
  'attendance.preferences.read',
  'attendance.preferences.write',
  'leave.requests.read',
  'leave.requests.read.all',
  'leave.requests.write',
  'leave.requests.decide',
  'leave.balances.read',
  'leave.balances.read.all',
  'leave.balances.adjust',
  'leave.types.read',
  'leave.types.write',
  'timesheets.read',
  'timesheets.read.all',
  'timesheets.write',
  'timesheets.submit',
  'timesheets.decide',
  'payroll.payslips.read',
  'payroll.payslips.read.all',
  'payroll.employee-profile.read',
  'payroll.employee-profile.read.all',
  'payroll.employee-profile.write',
  'payroll.preview.read',
  'payroll.ledger.read',
  'payroll.ledger.read.all',
  'payroll.runs.read',
  'payroll.runs.write',
  'payroll.runs.calculate',
  'payroll.runs.correct',
  'payroll.adjustments.write',
  'payroll.advances.read',
  'payroll.advances.request',
  'payroll.advances.approve',
  'payroll.payments.read',
  'payroll.payments.write',
  'payroll.calendars.read',
  'payroll.calendars.write',
  'payroll.components.read',
  'payroll.components.write',
  'payroll.policy.read',
  'payroll.policy.write',
  'payroll.compliance.read',
  'payroll.compliance.read.all',
  'payroll.compliance.write',
  'teams.read',
  'teams.write',
  'projects.read',
  'projects.write',
  'files.read',
  'files.read.all',
  'files.write',
  'shifts.read',
  'shifts.write',
];

export const EMPLOYEE_PERMISSIONS: string[] = [
  'organizations.read',
  'employees.read',
  'attendance.read',
  'attendance.write',
  'leave.types.read',
  'leave.requests.read',
  'leave.requests.write',
  'leave.balances.read',
  'timesheets.read',
  'timesheets.write',
  'timesheets.submit',
  'payroll.payslips.read',
  'payroll.employee-profile.read',
  'payroll.preview.read',
  'teams.read',
  'projects.read',
  'shifts.read',
  'files.read',
  'files.write',
];

export const EMPLOYEES: EmployeeSeedData[] = [
  {
    empNo: 'EMP-001',
    firstName: 'Rahul',
    lastName: 'Sharma',
    email: 'admin@apexdynamics.com',
    role: 'ORG_ADMIN',
    gross: 180000,
  },
  {
    empNo: 'EMP-002',
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'priya.patel@apexdynamics.com',
    role: 'EMPLOYEE',
    gross: 125000,
  },
  {
    empNo: 'EMP-003',
    firstName: 'Vikram',
    lastName: 'Malhotra',
    email: 'vikram.malhotra@apexdynamics.com',
    role: 'MANAGER',
    gross: 155000,
  },
  {
    empNo: 'EMP-004',
    firstName: 'Ananya',
    lastName: 'Iyer',
    email: 'ananya.iyer@apexdynamics.com',
    role: 'MANAGER',
    gross: 140000,
  },
  {
    empNo: 'EMP-005',
    firstName: 'Arjun',
    lastName: 'Das',
    email: 'arjun.das@apexdynamics.com',
    role: 'EMPLOYEE',
    gross: 95000,
  },
  {
    empNo: 'EMP-006',
    firstName: 'Sneha',
    lastName: 'Kulkarni',
    email: 'sneha.kulkarni@apexdynamics.com',
    role: 'MANAGER',
    gross: 135000,
  },
  {
    empNo: 'EMP-007',
    firstName: 'Rohan',
    lastName: 'Nair',
    email: 'rohan.nair@apexdynamics.com',
    role: 'EMPLOYEE',
    gross: 90000,
  },
  {
    empNo: 'EMP-008',
    firstName: 'Pooja',
    lastName: 'Verma',
    email: 'pooja.verma@apexdynamics.com',
    role: 'EMPLOYEE',
    gross: 80000,
  },
  {
    empNo: 'EMP-009',
    firstName: 'Karthik',
    lastName: 'Sundaram',
    email: 'karthik.sundaram@apexdynamics.com',
    role: 'EMPLOYEE',
    gross: 95000,
  },
  {
    empNo: 'EMP-010',
    firstName: 'Divya',
    lastName: 'Menon',
    email: 'divya.menon@apexdynamics.com',
    role: 'EMPLOYEE',
    gross: 85000,
  },
];

export const HOLIDAYS: HolidaySeedData[] = [
  { date: '2026-10-02', name: 'Mahatma Gandhi Jayanti', isOptional: false },
  { date: '2026-11-01', name: 'Kannada Rajyotsava', isOptional: false },
  { date: '2026-11-08', name: 'Diwali (Deepavali)', isOptional: false },
  { date: '2026-09-14', name: 'Ganesh Chaturthi (Optional)', isOptional: true },
  { date: '2026-09-24', name: 'Onam (Optional)', isOptional: true },
  { date: '2026-11-24', name: 'Guru Nanak Jayanti (Optional)', isOptional: true },
];
